/*
 * This file is generated by jOOQ.
 */
package com.quocard.bookmanagement.jooq;


import com.quocard.bookmanagement.jooq.tables.BookAuthors;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_BOOK_AUTHORS_AUTHOR_ID = Internal.createIndex(DSL.name("idx_book_authors_author_id"), BookAuthors.BOOK_AUTHORS, new OrderField[] { BookAuthors.BOOK_AUTHORS.AUTHOR_ID }, false);
}
