/*
 * This file is generated by jOOQ.
 */
package com.quocard.bookmanagement.jooq;


import com.quocard.bookmanagement.jooq.tables.Authors;
import com.quocard.bookmanagement.jooq.tables.BookAuthors;
import com.quocard.bookmanagement.jooq.tables.Books;
import com.quocard.bookmanagement.jooq.tables.records.AuthorsRecord;
import com.quocard.bookmanagement.jooq.tables.records.BookAuthorsRecord;
import com.quocard.bookmanagement.jooq.tables.records.BooksRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AuthorsRecord> AUTHORS_PKEY = Internal.createUniqueKey(Authors.AUTHORS, DSL.name("authors_pkey"), new TableField[] { Authors.AUTHORS.ID }, true);
    public static final UniqueKey<BookAuthorsRecord> BOOK_AUTHORS_PKEY = Internal.createUniqueKey(BookAuthors.BOOK_AUTHORS, DSL.name("book_authors_pkey"), new TableField[] { BookAuthors.BOOK_AUTHORS.BOOK_ID, BookAuthors.BOOK_AUTHORS.AUTHOR_ID }, true);
    public static final UniqueKey<BooksRecord> BOOKS_PKEY = Internal.createUniqueKey(Books.BOOKS, DSL.name("books_pkey"), new TableField[] { Books.BOOKS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BookAuthorsRecord, AuthorsRecord> BOOK_AUTHORS__BOOK_AUTHORS_AUTHOR_ID_FKEY = Internal.createForeignKey(BookAuthors.BOOK_AUTHORS, DSL.name("book_authors_author_id_fkey"), new TableField[] { BookAuthors.BOOK_AUTHORS.AUTHOR_ID }, Keys.AUTHORS_PKEY, new TableField[] { Authors.AUTHORS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<BookAuthorsRecord, BooksRecord> BOOK_AUTHORS__BOOK_AUTHORS_BOOK_ID_FKEY = Internal.createForeignKey(BookAuthors.BOOK_AUTHORS, DSL.name("book_authors_book_id_fkey"), new TableField[] { BookAuthors.BOOK_AUTHORS.BOOK_ID }, Keys.BOOKS_PKEY, new TableField[] { Books.BOOKS.ID }, true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION);
}
