/*
 * This file is generated by jOOQ.
 */
package com.quocard.bookmanagement.jooq;


import com.quocard.bookmanagement.jooq.tables.Authors;
import com.quocard.bookmanagement.jooq.tables.BookAuthors;
import com.quocard.bookmanagement.jooq.tables.Books;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.authors</code>.
     */
    public final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.book_authors</code>.
     */
    public final BookAuthors BOOK_AUTHORS = BookAuthors.BOOK_AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public final Books BOOKS = Books.BOOKS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Authors.AUTHORS,
            BookAuthors.BOOK_AUTHORS,
            Books.BOOKS
        );
    }
}
