/*
 * This file is generated by jOOQ.
 */
package com.quocard.bookmanagement.jooq;


import com.quocard.bookmanagement.jooq.tables.Authors;
import com.quocard.bookmanagement.jooq.tables.BookAuthors;
import com.quocard.bookmanagement.jooq.tables.Books;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.authors</code>.
     */
    public static final Authors AUTHORS = Authors.AUTHORS;

    /**
     * The table <code>public.book_authors</code>.
     */
    public static final BookAuthors BOOK_AUTHORS = BookAuthors.BOOK_AUTHORS;

    /**
     * The table <code>public.books</code>.
     */
    public static final Books BOOKS = Books.BOOKS;
}
