/*
 * This file is generated by jOOQ.
 */
package com.quocard.bookmanagement.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Books implements Serializable {

    private static final long serialVersionUID = 1L;

    private final Long id;
    private final String title;
    private final Integer price;
    private final String publicationStatus;

    public Books(Books value) {
        this.id = value.id;
        this.title = value.title;
        this.price = value.price;
        this.publicationStatus = value.publicationStatus;
    }

    public Books(
        Long id,
        String title,
        Integer price,
        String publicationStatus
    ) {
        this.id = id;
        this.title = title;
        this.price = price;
        this.publicationStatus = publicationStatus;
    }

    /**
     * Getter for <code>public.books.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Getter for <code>public.books.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Getter for <code>public.books.price</code>.
     */
    public Integer getPrice() {
        return this.price;
    }

    /**
     * Getter for <code>public.books.publication_status</code>.
     */
    public String getPublicationStatus() {
        return this.publicationStatus;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Books other = (Books) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.title == null) {
            if (other.title != null)
                return false;
        }
        else if (!this.title.equals(other.title))
            return false;
        if (this.price == null) {
            if (other.price != null)
                return false;
        }
        else if (!this.price.equals(other.price))
            return false;
        if (this.publicationStatus == null) {
            if (other.publicationStatus != null)
                return false;
        }
        else if (!this.publicationStatus.equals(other.publicationStatus))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.title == null) ? 0 : this.title.hashCode());
        result = prime * result + ((this.price == null) ? 0 : this.price.hashCode());
        result = prime * result + ((this.publicationStatus == null) ? 0 : this.publicationStatus.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Books (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(price);
        sb.append(", ").append(publicationStatus);

        sb.append(")");
        return sb.toString();
    }
}
